### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by JavierTimal** [TypedProject/ts-gphoto2-driver#21]
Please help me and guide me, I can't run the proyect, I clone de repository, then I run "npm install" command, then I run "npm install @typedproject/gphoto2-driver" and then I want to run the "npm run install:examples" to try the app, but I can't because when I run the  "npm run install:examples" command, the terminal show me error that I can't understand, what I do bad?

**Comment by Romakita** [comment]
What is your error exactly?

**Comment by gentilmente** [comment]
`me@here ts-gphoto2-driver % npm install                                
removed 4 packages and audited 1904 packages in 8.39s

43 packages are looking for funding
  run `npm fund` for details

found 6 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
me@here ts-gphoto2-driver % 
`
then
`me@here ts-gphoto2-driverx % npm install @typedproject/gphoto2-driver
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "@typedproject/gphoto2-driver" under a package
npm ERR! also called "@typedproject/gphoto2-driver". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR! 
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2021-01-26T20_07_09_592Z-debug.log`

**Comment by gentilmente** [comment]
HI I get this..

`> node-gyp rebuild

  CXX(target) Release/obj.target/binding/src/binding.o
In file included from ../src/binding.cc:7:
In file included from ../../nan/nan.h:2884:
../../nan/nan_typedarray_contents.h:34:43: warning: 'GetContents' is deprecated: Use GetBackingStore. See
      http://crbug.com/v8/9908. [-Wdeprecated-declarations]
      data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
                                          ^
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:5202:3: note: 'GetContents' has been
      explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use GetBackingStore. See http://crbug.com/v8/9908.")
  ^
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8config.h:402:39: note: expanded from macro
      'V8_DEPRECATE_SOON'
# define V8_DEPRECATE_SOON(message) [[deprecated(message)]]
                                      ^
../src/binding.cc:222:43: error: too few arguments to function call, single argument 'isolate' was not
      specified
  bool persistent = info[3]->BooleanValue();
                    ~~~~~~~~~~~~~~~~~~~~~ ^
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:2855:3: note: 'BooleanValue' declared here
  bool BooleanValue(Isolate* isolate) const;
  ^
../src/binding.cc:253:38: error: too few arguments to function call, single argument 'context' was not
      specified
  size_t size = info[2]->Uint32Value();
                ~~~~~~~~~~~~~~~~~~~~ ^
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:2863:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8config.h:422:31: note: expanded from macro
      'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/binding.cc:360:23: error: no matching constructor for initialization of 'String::Utf8Value'
    String::Utf8Value _str(in);
                      ^    ~~
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3274:5: note: candidate constructor not
      viable: no known conversion from 'Local<v8::Value>' to 'const v8::String::Utf8Value' for 1st
      argument
    Utf8Value(const Utf8Value&) = delete;
    ^
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3267:5: note: candidate constructor not
      viable: requires 2 arguments, but 1 was provided
    Utf8Value(Isolate* isolate, Local<v8::Value> obj);
    ^
../src/binding.cc:447:23: error: no matching constructor for initialization of 'String::Utf8Value'
    String::Utf8Value _str(in);
                      ^    ~~
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3274:5: note: candidate constructor not
      viable: no known conversion from 'Local<v8::Value>' to 'const v8::String::Utf8Value' for 1st
      argument
    Utf8Value(const Utf8Value&) = delete;
    ^
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3267:5: note: candidate constructor not
      viable: requires 2 arguments, but 1 was provided
    Utf8Value(Isolate* isolate, Local<v8::Value> obj);
    ^
../src/binding.cc:521:38: error: too few arguments to function call, single argument 'context' was not
      specified
  size_t size = info[1]->Uint32Value();
                ~~~~~~~~~~~~~~~~~~~~ ^
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:2863:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8config.h:422:31: note: expanded from macro
      'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/binding.cc:550:44: error: too few arguments to function call, single argument 'context' was not
      specified
  uint32_t numZeros = info[1]->Uint32Value();
                      ~~~~~~~~~~~~~~~~~~~~ ^
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:2863:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8config.h:422:31: note: expanded from macro
      'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/binding.cc:582:3: error: no matching member function for call to 'Set'
  SET_SIZEOF(int8, int8_t);
  ^~~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:581:9: note: expanded from macro 'SET_SIZEOF'
  smap->Set(Nan::New<v8::String>( #name ).ToLocalChecked(), Nan::New<v8::Uint32>(static_cast<uint3...
  ~~~~~~^~~
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3639:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3642:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/binding.cc:583:3: error: no matching member function for call to 'Set'
  SET_SIZEOF(uint8, uint8_t);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:581:9: note: expanded from macro 'SET_SIZEOF'
  smap->Set(Nan::New<v8::String>( #name ).ToLocalChecked(), Nan::New<v8::Uint32>(static_cast<uint3...
  ~~~~~~^~~
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3639:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3642:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/binding.cc:584:3: error: no matching member function for call to 'Set'
  SET_SIZEOF(int16, int16_t);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:581:9: note: expanded from macro 'SET_SIZEOF'
  smap->Set(Nan::New<v8::String>( #name ).ToLocalChecked(), Nan::New<v8::Uint32>(static_cast<uint3...
  ~~~~~~^~~
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3639:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3642:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/binding.cc:585:3: error: no matching member function for call to 'Set'
  SET_SIZEOF(uint16, uint16_t);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:581:9: note: expanded from macro 'SET_SIZEOF'
  smap->Set(Nan::New<v8::String>( #name ).ToLocalChecked(), Nan::New<v8::Uint32>(static_cast<uint3...
  ~~~~~~^~~
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3639:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3642:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/binding.cc:586:3: error: no matching member function for call to 'Set'
  SET_SIZEOF(int32, int32_t);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:581:9: note: expanded from macro 'SET_SIZEOF'
  smap->Set(Nan::New<v8::String>( #name ).ToLocalChecked(), Nan::New<v8::Uint32>(static_cast<uint3...
  ~~~~~~^~~
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3639:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3642:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/binding.cc:587:3: error: no matching member function for call to 'Set'
  SET_SIZEOF(uint32, uint32_t);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:581:9: note: expanded from macro 'SET_SIZEOF'
  smap->Set(Nan::New<v8::String>( #name ).ToLocalChecked(), Nan::New<v8::Uint32>(static_cast<uint3...
  ~~~~~~^~~
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3639:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3642:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/binding.cc:588:3: error: no matching member function for call to 'Set'
  SET_SIZEOF(int64, int64_t);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:581:9: note: expanded from macro 'SET_SIZEOF'
  smap->Set(Nan::New<v8::String>( #name ).ToLocalChecked(), Nan::New<v8::Uint32>(static_cast<uint3...
  ~~~~~~^~~
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3639:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3642:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/binding.cc:589:3: error: no matching member function for call to 'Set'
  SET_SIZEOF(uint64, uint64_t);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:581:9: note: expanded from macro 'SET_SIZEOF'
  smap->Set(Nan::New<v8::String>( #name ).ToLocalChecked(), Nan::New<v8::Uint32>(static_cast<uint3...
  ~~~~~~^~~
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3639:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3642:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/binding.cc:590:3: error: no matching member function for call to 'Set'
  SET_SIZEOF(float, float);
  ^~~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:581:9: note: expanded from macro 'SET_SIZEOF'
  smap->Set(Nan::New<v8::String>( #name ).ToLocalChecked(), Nan::New<v8::Uint32>(static_cast<uint3...
  ~~~~~~^~~
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3639:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3642:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/binding.cc:591:3: error: no matching member function for call to 'Set'
  SET_SIZEOF(double, double);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:581:9: note: expanded from macro 'SET_SIZEOF'
  smap->Set(Nan::New<v8::String>( #name ).ToLocalChecked(), Nan::New<v8::Uint32>(static_cast<uint3...
  ~~~~~~^~~
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3639:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3642:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/binding.cc:593:3: error: no matching member function for call to 'Set'
  SET_SIZEOF(bool, bool);
  ^~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:581:9: note: expanded from macro 'SET_SIZEOF'
  smap->Set(Nan::New<v8::String>( #name ).ToLocalChecked(), Nan::New<v8::Uint32>(static_cast<uint3...
  ~~~~~~^~~
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3639:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3642:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/binding.cc:594:3: error: no matching member function for call to 'Set'
  SET_SIZEOF(byte, unsigned char);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:581:9: note: expanded from macro 'SET_SIZEOF'
  smap->Set(Nan::New<v8::String>( #name ).ToLocalChecked(), Nan::New<v8::Uint32>(static_cast<uint3...
  ~~~~~~^~~
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3639:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3642:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/binding.cc:595:3: error: no matching member function for call to 'Set'
  SET_SIZEOF(char, char);
  ^~~~~~~~~~~~~~~~~~~~~~
../src/binding.cc:581:9: note: expanded from macro 'SET_SIZEOF'
  smap->Set(Nan::New<v8::String>( #name ).ToLocalChecked(), Nan::New<v8::Uint32>(static_cast<uint3...
  ~~~~~~^~~
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3639:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/me/Library/Caches/node-gyp/14.4.0/include/node/v8.h:3642:37: note: candidate function not
      viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 20.2.0
gyp ERR! command "/usr/local/Cellar/node/14.4.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/me/Developer/PROYECTOS/BiblioHack/ts-gphoto2-driverx/examples/node_modules/ref
gyp ERR! node -v v14.4.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN @typedproject/gphoto2-driver-integration@1.0.0 No description
npm WARN @typedproject/gphoto2-driver-integration@1.0.0 No repository field.
npm WARN @typedproject/gphoto2-driver-integration@1.0.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ref@1.3.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ref@1.3.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/me/.npm/_logs/2021-01-26T20_17_14_692Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @typedproject/gphoto2-driverX@2.4.2 install:examples: `npm run build && cd examples && npm i`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @typedproject/gphoto2-driverX@2.4.2 install:examples script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by goooseman** [comment]
Check please if you have following libs from the `Prerequisite ` section of the README installed on your machine:
- libgphoto2
- pkg-config | dpkg (used for dependency checking)
- clang compiler

**Comment by gentilmente** [comment]
yes, I have all installed

**Comment by Romakita** [comment]
Should be fixed with v3
